class_order: class_orders/cifar100_order.yaml
dataset_root: /data/xuming/Hou_temp/RAPF/dataset_root/cifar100
workdir: /data/xuming/Hou_temp/RAPF
log_path: metric.json
model_name: ViT-B/16
prompt_template: a good photo of a {}.
batch_size: 128
initial_increment: 50
increment: 10
scenario: class
dataset: cifar100
num_workers: 16
train_batch_size: 100
epochs: 15
lr: 0.001
fp16: false
seed: 2
milestones:
- 4
- 10
beta: 2
mix_bias: 0.6
threshold: 0.55
shrinkage: false
